---
- name: Install packages
  package:
    name: "{{ webserver_packages }}"
    state: latest

- name: Add nginx config
  copy:
    dest: /etc/nginx/nginx.conf
    src: etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx

- name: Add nginx site-specific configs
  copy:
    dest: "/{{ item.conf }}"
    src: "{{ item.conf }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ webserver_static_sites }}"
  notify: Reload nginx

- name: Ensure content dirs exist
  file:
    path: "/var/www/{{ item.name }}/"
    mode: 0755
    state: directory
  with_items: "{{ webserver_static_sites }}"

- name: Upload content
  synchronize:
    src: "{{ item.root }}/"
    dest: "/var/www/{{ item.name }}/"
    delete: yes
    rsync_opts:
      - "--rsh=rsh"
  with_items: "{{ webserver_static_sites }}"

- name: Enable sites
  file:
    src: "/{{ item.conf }}"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}"
    state: link
  with_items: "{{ webserver_static_sites }}"
