---
- name: Install packages
  package:
    name: "{{ webserver_packages }}"
    state: latest

- name: Add nginx config
  copy:
    dest: /etc/nginx/nginx.conf
    src: etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx
