on: push

jobs:
  build-html-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          make generator/html_generator/html-generator
      - uses: actions/upload-artifact@v2
        with:
          name: html-generator
          path: generator/html_generator/html-generator

  generate:
    runs-on: ubuntu-latest
    needs: build-html-generator
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/download-artifact@v2
        with:
          name: html-generator
          path: generator/html_generator
      - run: |
          python generator/generate.py
      - run: |
          python generator/generate_homepage.py
      - uses: actions/upload-artifact@v2
        with:
          name: index-page
          path: static/index.html

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        name: index-page
        path: static
    - uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
