on: push

jobs:
  build-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/build-generator
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python generator/generate_homepage.py
      - uses: actions/upload-artifact@v2
        with:
          name: index-page
          path: content/index.html
  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        name: index-page
        path: content
    - uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
