on: push

jobs:
  build-html-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
      - name: Build compiler image
        run: |
          dockers/html-generator-builder/build_docker_image.sh
      - name: Run html generator tests
        run: |
          generator/html_generator/build.sh test
      - name: Compile html-generator
        run: |
          generator/html_generator/build.sh
      - name: Upload html-generator artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-generator
          path: generator/html_generator/html-generator

  generate:
    runs-on: ubuntu-latest
    needs: build-html-generator
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Download html-generator
        uses: actions/download-artifact@v2
        with:
          name: html-generator
          path: generator/html_generator
      - name: Make html-generator executable
        run: |
          chmod +x generator/html_generator/html-generator
      - name: Run html-generator and generate index
        run: |
          python generator/generate.py
      - name: Upload generated html files
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: static/

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - name: Check out repo
      uses: actions/checkout@v1
    - name: Download generated html files
      uses: actions/download-artifact@v2
      with:
        name: static
        path: static
    - name: Run Ansible deployment playbook
      uses: ./dockers/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
