on: push

jobs:
  build-parser-builder-image:
    runs-on: ubuntu-latest
    rules:
      changes:
        - dockers/markdown_parser_builder/**/*
    steps:
    - uses: actions/checkout@v1
    - run: | 
        dockers/markdown_parser_builder/build_docker_image.sh

  build-generator:
    runs-on: ubuntu-latest
    needs: build-parser-builder-image
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/build-generator
    - uses: actions/upload-artifact@v2
      with:
        name: markup-parser
        path: generator/convert_markup/dist-newstyle/build/x86_64-linux/ghc-8.8.4/hs-blog-0.1.0.0/x/haskell-blog-generator/build/haskell-blog-generator/haskell-blog-generator

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python generator/generate_homepage.py
      - uses: actions/upload-artifact@v2
        with:
          name: index-page
          path: content/index.html
  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        name: index-page
        path: content
    - uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
